#!/bin/sh
if [ "$1" = "remove" ]; then
	rm -rf /usr/lib/enigma2/python/Plugins/Extensions/MovieCockpit > /dev/null 2>&1
	echo "MovieCockpit plugin removed successfully."
else
	find /usr/lib/enigma2/python/Plugins/Extensions/MovieCockpit -type f -name "*.pyo" -exec rm -f {} \; > /dev/null 2>&1
fi
exit 0
